const { mkdirSync, writeFileSync } = require('node:fs');
const { resolve } = require('node:path');
const ts = require('typescript');
const { logger } = require('./log');

const log = logger('TYPES');
const rootDir = resolve(__dirname, '..');
const outDir = resolve(rootDir, 'dist');
const entry = resolve(rootDir, 'typings', 'index.d.ts');

/*
 * The published package needs one type entry per module format: an ESM one in the
 * `dist/esm` folder (flagged as `type: module`) and a CJS one using `export =` to
 * describe the callable `module.exports` of `dist/cjs/index.js`.
 */
main();

function main() {
   log('reading public api from', entry);
   const { values, types } = publicApi(entry);

   write('esm', esmTypes());
   write('cjs', cjsTypes(values, types));
   log('done');
}

function write(format, content) {
   const file = resolve(outDir, format, 'index.d.ts');
   mkdirSync(resolve(file, '..'), { recursive: true });
   writeFileSync(file, content, 'utf8');
   log('generated', file);
}

/**
 * Splits the exports of the hand-written typings into those with a value at
 * runtime and those that are types only.
 */
function publicApi(fileName) {
   const program = ts.createProgram([fileName], {
      module: ts.ModuleKind.CommonJS,
      moduleResolution: ts.ModuleResolutionKind.Node10,
      skipLibCheck: true,
      strict: true,
   });
   const checker = program.getTypeChecker();
   const source = checker.getSymbolAtLocation(program.getSourceFile(fileName));

   const values = [];
   const types = [];

   for (const exported of checker.getExportsOfModule(source)) {
      if (exported.name === 'default') {
         continue;
      }

      let symbol = exported;
      while (symbol.flags & ts.SymbolFlags.Alias) {
         symbol = checker.getAliasedSymbol(symbol);
      }

      (symbol.flags & ts.SymbolFlags.Value ? values : types).push(exported.name);
   }

   return { values: values.sort(), types: types.sort() };
}

function esmTypes() {
   return `${banner()}
export * from '../typings/index.js';
export { simpleGit as default } from '../typings/index.js';
`;
}

function cjsTypes(values, types) {
   return `${banner()}
import {
${list(values)}
} from '../typings/index.js';
import type {
${list(types)}
} from '../typings/index.js';

// Overloads of \`SimpleGitFactory\`, repeated to allow merging with the namespace below.
declare function simpleGitFactory(baseDir?: string, options?: Partial<SimpleGitOptions>): SimpleGit;
declare function simpleGitFactory(baseDir: string): SimpleGit;
declare function simpleGitFactory(options: Partial<SimpleGitOptions>): SimpleGit;

declare namespace simpleGitFactory {
   export {
${list(values, 6)}
   };
   export type {
${list(types, 6)}
   };
   export { simpleGit as default };
}

export = simpleGitFactory;
`;
}

function list(names, indent = 3) {
   return names.map((name) => `${' '.repeat(indent)}${name},`).join('\n');
}

function banner() {
   return `// Generated by scripts/build-types.js - do not edit.\n`;
}
