name: CI

on:
   push:
      branches: [main, canary/v4]
   pull_request:
      branches: [main, canary/v4]

permissions:
   contents: read

jobs:
   build-ubuntu:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [20, 22, 23, 24, 25]
      steps:
         - uses: actions/checkout@v6
         - uses: pnpm/action-setup@v4
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v6
           with:
              node-version: ${{ matrix.node-version }}
              cache: pnpm
         - run: pnpm install --frozen-lockfile
         - run: pnpm build
         - name: Test
           env:
              GIT_AUTHOR_NAME: 'Simple Git Tests'
              GIT_AUTHOR_EMAIL: 'tests@simple-git.dev'
           run: pnpm test
         - run: pnpm build:pkg
         - run: pnpm test:consumer

   build-windows:
      runs-on: windows-latest
      steps:
         - uses: actions/checkout@v6
         - uses: pnpm/action-setup@v4
         - name: Use Node.js 24
           uses: actions/setup-node@v6
           with:
              node-version: 24
              cache: pnpm
         - run: pnpm install --frozen-lockfile
         - run: pnpm build
         - name: Test
           env:
              GIT_AUTHOR_NAME: 'Simple Git Tests'
              GIT_AUTHOR_EMAIL: 'tests@simple-git.dev'
           run: pnpm test:win
