name: Lint

on:
   push:
      branches: [main, canary/v4]
   pull_request:
      branches: [main, canary/v4]

permissions:
   contents: read

jobs:
   lint:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v6
         - uses: pnpm/action-setup@v4
         - name: Use Node.js
           uses: actions/setup-node@v6
           with:
              node-version: 24
              cache: pnpm
         - run: pnpm install --frozen-lockfile
         - run: pnpm lint
