name: release-please

on:
   push:
      branches:
         - main

jobs:
   release-please:
      runs-on: ubuntu-latest
      steps:
         - uses: google-github-actions/release-please-action@v2
           id: release
           with:
              command: manifest
              token: ${{ secrets.GITHUB_TOKEN }}
              default-branch: main

         -  uses: actions/checkout@v2
            if: ${{ steps.release.outputs.release_created }}

         - uses: actions/setup-node@v1
           with:
              node-version: 16
              registry-url: 'https://registry.npmjs.org'
           if: ${{ steps.release.outputs.release_created }}

         - run: yarn
           if: ${{ steps.release.outputs.release_created }}

         - run: yarn workspace simple-git build
           if: ${{ steps.release.outputs.release_created }}

         - run: npm publish --dry-run ./simple-git/dist
           env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
           if: ${{ steps.release.outputs.release_created }}
